function [] = initiate(handles)
% create cells
handles.forces = [] ;
handles.groups = [] ;

handles.selected_forces = [] ;
handles.selected_groups = [] ;

handles.func_str_axes_right = '' ;
handles.func_show_axes_right = 0 ;

handles.last_ibw_path = pwd ;
% set axes properties
set(handles.axes_left,...
    'Box', 'on',...
    'LineWidth', 1.2,...
    'XMinorTick', 'on',...
    'YMinorTick', 'on',...
    'TickLength', [0.007 0.007],...
    'FontName', 'Lucida Bright',...
    'FontSize', 12);
set(handles.axes_right,...
    'Box', 'on',...
    'LineWidth', 1.2,...
    'XMinorTick', 'on',...
    'YMinorTick', 'on',...
    'TickLength', [0.007 0.007],...
    'FontName', 'Lucida Bright',...
    'FontSize', 12);

xlabel('Separation [nm]') ;
ylabel('Force [nN]') ;

refresh_tables(handles,true) ;
guidata(handles.figure_main, handles);
